-- I did not wrote this code myself. It was generated by ChatGPT based on my instructions. It needs to be reviewed and tested.


-- Seed data for collections, keywords, and providers (idempotent)
-- This script can be executed repeatedly without creating duplicates.

-- Root catalog (optional)
INSERT INTO catalog (stac_version, type, title, description)
SELECT '1.0.0', 'Catalog', 'STAC Atlas Root', 'Root STAC catalog for tests'
WHERE NOT EXISTS (
  SELECT 1 FROM catalog WHERE title = 'STAC Atlas Root'
);

-- Keywords
INSERT INTO keywords (keyword) VALUES
  ('sentinel-2'),
  ('optical'),
  ('multispectral'),
  ('landsat'),
  ('modis'),
  ('daily'),
  ('thermal'),
  ('visible')
ON CONFLICT (keyword) DO NOTHING;

-- Providers
INSERT INTO providers (provider) VALUES
  ('ESA'),
  ('USGS'),
  ('NASA')
ON CONFLICT (provider) DO NOTHING;

-- Sentinel-2 L2A
DO $$
DECLARE
  v_collection_id INTEGER;
  v_provider_id INTEGER;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM collection WHERE title = 'Sentinel-2 L2A Collection'
  ) THEN
    INSERT INTO collection (
      stac_version, type, title, description, license,
      spatial_extend, temporal_extend_start, temporal_extend_end,
      is_api, is_active, full_json, created_at, updated_at
    ) VALUES (
      '1.0.0', 'Collection', 'Sentinel-2 L2A Collection',
      'Sentinel-2 Level-2A processed imagery from Copernicus', 'CC-BY-4.0',
      ST_MakeEnvelope(-180, -90, 180, 90, 4326),
      '2015-06-23T00:00:00Z'::timestamp, '2025-01-01T00:00:00Z'::timestamp,
      TRUE, TRUE,
      jsonb_build_object(
        'id','sentinel-2-l2a',
        'stac_version','1.0.0',
        'title','Sentinel-2 L2A Collection'
      ),
      '2018-01-01T00:00:00Z'::timestamp,
      '2025-01-01T00:00:00Z'::timestamp
    );
  END IF;

  SELECT id INTO v_collection_id FROM collection WHERE title = 'Sentinel-2 L2A Collection' ORDER BY id DESC LIMIT 1;

  -- Ensure temporal end is set if previously null
  UPDATE collection
  SET temporal_extend_end = updated_at
  WHERE id = v_collection_id AND temporal_extend_end IS NULL;

  INSERT INTO collection_keywords (collection_id, keyword_id)
  SELECT v_collection_id, k.id FROM keywords k
  WHERE k.keyword IN ('sentinel-2','optical','multispectral')
    AND NOT EXISTS (
      SELECT 1 FROM collection_keywords ck WHERE ck.collection_id = v_collection_id AND ck.keyword_id = k.id
    );

  SELECT id INTO v_provider_id FROM providers WHERE provider = 'ESA';
  IF v_provider_id IS NOT NULL THEN
    INSERT INTO collection_providers (collection_id, provider_id, collection_provider_roles)
    SELECT v_collection_id, v_provider_id, 'producer,licensor'
    WHERE NOT EXISTS (
      SELECT 1 FROM collection_providers cp WHERE cp.collection_id = v_collection_id AND cp.provider_id = v_provider_id
    );
  END IF;
END $$;

-- Landsat 8 Level-1
DO $$
DECLARE
  v_collection_id INTEGER;
  v_provider_id INTEGER;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM collection WHERE title = 'Landsat 8 Level-1'
  ) THEN
    INSERT INTO collection (
      stac_version, type, title, description, license,
      spatial_extend, temporal_extend_start, temporal_extend_end,
      is_api, is_active, full_json, created_at, updated_at
    ) VALUES (
      '1.0.0', 'Collection', 'Landsat 8 Level-1',
      'Landsat 8 Collection 1 Level 1 data', 'CC0-1.0',
      ST_MakeEnvelope(-180, -90, 180, 90, 4326),
      '2013-02-11T00:00:00Z'::timestamp, '2024-06-01T00:00:00Z'::timestamp,
      TRUE, TRUE,
      jsonb_build_object(
        'id','landsat-8-l1',
        'stac_version','1.0.0',
        'title','Landsat 8 Level-1'
      ),
      '2013-02-11T00:00:00Z'::timestamp,
      '2024-06-01T00:00:00Z'::timestamp
    );
  END IF;

  SELECT id INTO v_collection_id FROM collection WHERE title = 'Landsat 8 Level-1' ORDER BY id DESC LIMIT 1;

  -- Ensure temporal end is set if previously null
  UPDATE collection
  SET temporal_extend_end = updated_at
  WHERE id = v_collection_id AND temporal_extend_end IS NULL;

  INSERT INTO collection_keywords (collection_id, keyword_id)
  SELECT v_collection_id, k.id FROM keywords k
  WHERE k.keyword IN ('landsat','optical','multispectral')
    AND NOT EXISTS (
      SELECT 1 FROM collection_keywords ck WHERE ck.collection_id = v_collection_id AND ck.keyword_id = k.id
    );

  SELECT id INTO v_provider_id FROM providers WHERE provider = 'USGS';
  IF v_provider_id IS NOT NULL THEN
    INSERT INTO collection_providers (collection_id, provider_id, collection_provider_roles)
    SELECT v_collection_id, v_provider_id, 'producer'
    WHERE NOT EXISTS (
      SELECT 1 FROM collection_providers cp WHERE cp.collection_id = v_collection_id AND cp.provider_id = v_provider_id
    );
  END IF;
END $$;

-- MODIS Daily
DO $$
DECLARE
  v_collection_id INTEGER;
  v_provider_id INTEGER;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM collection WHERE title = 'MODIS Daily'
  ) THEN
    INSERT INTO collection (
      stac_version, type, title, description, license,
      spatial_extend, temporal_extend_start, temporal_extend_end,
      is_api, is_active, full_json, created_at, updated_at
    ) VALUES (
      '1.0.0', 'Collection', 'MODIS Daily',
      'MODIS daily composites from NASA Earth Observatories', 'CC0-1.0',
      ST_MakeEnvelope(-180, -90, 180, 90, 4326),
      '2000-02-24T00:00:00Z'::timestamp, '2023-12-31T00:00:00Z'::timestamp,
      TRUE, TRUE,
      jsonb_build_object(
        'id','modis',
        'stac_version','1.0.0',
        'title','MODIS Daily'
      ),
      '2000-02-24T00:00:00Z'::timestamp,
      '2023-12-31T00:00:00Z'::timestamp
    );
  END IF;

  SELECT id INTO v_collection_id FROM collection WHERE title = 'MODIS Daily' ORDER BY id DESC LIMIT 1;

  -- Ensure temporal end is set if previously null
  UPDATE collection
  SET temporal_extend_end = updated_at
  WHERE id = v_collection_id AND temporal_extend_end IS NULL;

  INSERT INTO collection_keywords (collection_id, keyword_id)
  SELECT v_collection_id, k.id FROM keywords k
  WHERE k.keyword IN ('modis','daily','thermal','visible')
    AND NOT EXISTS (
      SELECT 1 FROM collection_keywords ck WHERE ck.collection_id = v_collection_id AND ck.keyword_id = k.id
    );

  SELECT id INTO v_provider_id FROM providers WHERE provider = 'NASA';
  IF v_provider_id IS NOT NULL THEN
    INSERT INTO collection_providers (collection_id, provider_id, collection_provider_roles)
    SELECT v_collection_id, v_provider_id, 'producer,licensor'
    WHERE NOT EXISTS (
      SELECT 1 FROM collection_providers cp WHERE cp.collection_id = v_collection_id AND cp.provider_id = v_provider_id
    );
  END IF;
END $$;
