services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - path: .env
        required: false
    environment:
      - PORT=3000
